DROP DATABASE NFT_MARKET;
CREATE DATABASE NFT_MARKET;

USE NFT_MARKET;

CREATE TABLE USER_TYPE(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ROLE VARCHAR(50),
ABOUT VARCHAR(255));

CREATE TABLE [USER](
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NAME] VARCHAR(80) NOT NULL UNIQUE,
ID_TYPE INT NOT NULL FOREIGN KEY REFERENCES USER_TYPE(ID),
MAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(17),
DATE_OF_BIRTH DATE,
ADDRESS VARCHAR (255),
PASSWORD VARCHAR (255) NOT NULL);

CREATE TABLE ART_CATEGORY(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NAME] VARCHAR(255));

CREATE TABLE ART_TYPE(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NAME] VARCHAR(255));

CREATE TABLE AUTHOR(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(255) NOT NULL,
LASTNAME VARCHAR(255),
AGE INT ,
COUNTRY VARCHAR(255),
ABOUT VARCHAR(255));

CREATE TABLE ARTWORK(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NAME] VARCHAR(255) NOT NULL,
ID_CATEGORY INT FOREIGN KEY REFERENCES ART_CATEGORY(ID),
ID_TYPE INT NOT NULL FOREIGN KEY REFERENCES ART_TYPE(ID),
ID_AUTHOR INT NOT NULL FOREIGN KEY REFERENCES AUTHOR(ID),
CREATE_DATE DATETIME2,
ADD_DATE DATETIME2,
DESCRIP VARCHAR(255),
PRICE DECIMAL (14,6));

CREATE TABLE LOTS(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NAME] VARCHAR(255),
ARTWORK_ID INT FOREIGN KEY REFERENCES ARTWORK(ID),
START_PRICE DECIMAL (14,6),
FINAL_PRICE DECIMAL (14,6),
START_TIME DATETIME2,
END_TIME DATETIME2);

CREATE TABLE DEALS(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
SELLER_ID INT FOREIGN KEY REFERENCES [USER](ID),
BUYER_ID INT FOREIGN KEY REFERENCES [USER](ID),
LOT_ID INT FOREIGN KEY REFERENCES LOTS(ID)
);